.TH "u3-tool" 1
.SH NAME
u3-tool \- Tool for controlling the special features of an U3 USB Flash disk. 
.SH SYNOPSIS
.B u3-tool [-cdDehiuvV] [-l
.I cd image
.B ] [-p
.I cd size
.B ]
.I device
.SH DESCRIPTION
This tool can be used to control some of the special features of U3 Flash disks.
.SH OPTIONS
.IP -c
Change password
.IP -d
Disable device security
.IP -D
Dump all raw info(for debug)
.IP -e
Enable device security
.IP -h
Print this help message
.IP -i
Display device info
.IP "-l <cd image>"
Load CD image into device
.IP "-p <cd size>"
Repartition device
.IP -u
Unlock device
.IP -v
Use verbose output
.IP -V
Print version information
